{{- $ports := .Values.master.configuration.ports }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "seaweedfs.name" . }}-volume
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: "swfs-volume"
    port: {{ $ports.http }}
    targetPort: {{ $ports.http }}
    protocol: TCP
  - name: "swfs-volume-grpc"
    port: {{ $ports.grpc }}
    targetPort: {{ $ports.grpc }}
    protocol: TCP
{{- if and .Values.global.monitoring.enabled $ports.metrics }}
  - name: "metrics"
    port: {{ $ports.metrics }}
    targetPort: {{ $ports.metrics }}
    protocol: TCP
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    app.kubernetes.io/component: volume